### ISSUE TITLE
변수, @supports, @media, scss nesting

### ISSUE THREAD

**Issue by bgyoons** [bgyoons/Study-with-me#35]
### 해당 학습 부분 목차

8주차 · 파트 02
[DAY 36] CSS 심화 (3)

### 학습 내용

명시도 : 태그 선택 > 1점, 가상 클래스 선택자 > 10점

#### 변수

```css
:root(CSS 선택자에 다 가능) {
    --[변수이름]: 값
}

div {
    프로퍼티: var(--[변수이름])
}
```

#### `@supports`

```css
/** and/or를 통해 논리곱/합 연산자를 사용할 수 있음 **/
/** 변수가 있는지 확인할 수도 있음 **/

@supports ([판단할 프로퍼티/기능]) { 
    /* 지원하는 경우에 적용되는 스타일 */
}

@supports not ([판단할 프로퍼티/기능]) {
    /* 지원하지 않는 경우에 적용되는 스타일 */
}

/** selector는 CSS 선택자의 지원 여부 **/
@supports (selector([CSS 선택자])) {
    /* 지원하지 않는 경우에 적용되는 스타일 */
}
```

#### `@media`

```css
/* 타입에는 screen, print, tv ...이 있음 */
/* 기본값은 all이기 때문에 타입 and는 생략 가능 */
/* and 연산자를 통해 조건/기능 추가 가능 */
/* not 연산자를 사용하려면 타입을 반드시 적어야 함 */
/* ,(쉼표)를 통해 미디어 쿼리 추가 가능 */
/* orientation: portrait 을 조건에 넣으면 세로 너비가 가로 너비보다 긴 상황을 의미, 대표적으로 모바일 디바이스, landscape는 반대 상황 */

@media 타입 and (조건/기능) {
    /* 조건에 해당하는 스타일 재정의 */
}
```

[media 규칙들 - media fetures](https://developer.mozilla.org/en-US/docs/Web/CSS/@media#media_features)

link 태그에 media 속성에 조건(media 규칙)을 통해서도 파일별로 미디어 쿼리를 적용할 수 있음
```html
<link rel="stylesheet" src="./css/media.css" media="max-width: 700px">
```

#### SCSS

중첩 문법 내부에서 `&`를 통해 상위 선택자를 참조할 수 있다.

```scss
text {
    &-small { /* style */ }   /* text-small */
    &-medium { /* style */ }  /* text-medium */
    &-large { /* style */ }  /* text-large */
}
```

@at-규칙

반복되는 프로퍼티 글자를 묶어서 중첩을 통해 스타일 적용 가능

```scss
margin {
    top: 10px; /* margin-top */
    left: 10px;
}
```

! 플래그(!global, !default, ...)

데이터 보간 

```scss
$path: "./src/..."
$name: "hello"

div {
    background-image: url("#{$path}/#{name}.png")
}

.container-#{$name} {  /* .container-hello와 동일 */
    /* style */
}
```
